FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y build-essential unzip
RUN apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
RUN apt-get install -y libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev
RUN apt-get install -y wget

WORKDIR /source
RUN wget https://github.com/opencv/opencv/archive/2.4.13.2.zip && unzip 2.4.13.2.zip && rm 2.4.13.2.zip
WORKDIR /source/opencv-2.4.13.2/build
RUN cmake -D CMAKE_BUILD_TYPE=Release \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D WITH_TBB=ON \
#-D BUILD_TBB=ON \
-D WITH_CUDA=ON \
-D CUDA_FAST_MATH=ON \
-D ENABLE_FAST_MATH=ON \ 
-D WITH_CUBLAS=ON \
-D WITH_CUFFT=ON \
-D WITH_NVCUVID=ON \
-D WITH_OPENMP=ON \
-D WITH_IPP=ON \
-D WITH_CSTRIPES=ON \
-D WITH_OPENCL=ON \
-D WITH_FFMPEG=ON \
-D WITH_CUDNN=ON \
-D OPENCV_DNN_CUDA=ON ..

RUN make -j16 
RUN make install

COPY training /home/
